/* tslint:disable */
/* eslint-disable */
/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AbsenceCalendarsCreateCalendarRequest } from '../models';
// @ts-ignore
import { AbsenceCalendarsCreateCalendarRequestDaysOffInner } from '../models';
// @ts-ignore
import { AbsenceCalendarsCreateCalendarResponse } from '../models';
// @ts-ignore
import { AbsenceCalendarsListResponse } from '../models';
// @ts-ignore
import { AbsenceCalendarsUpdateByIdRequest } from '../models';
// @ts-ignore
import { AbsenceCalendarsUpdateByIdRequestDaysOffInner } from '../models';
// @ts-ignore
import { AbsenceCalendarsUpdateByIdResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AbsenceCalendarsApi - axios parameter creator
 * @export
 */
export const AbsenceCalendarsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Absence Calendar
         * @param {AbsenceCalendarsCreateCalendarRequest} [absenceCalendarsCreateCalendarRequest] Create a Absence Calendar
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCalendar: async (absenceCalendarsCreateCalendarRequest?: AbsenceCalendarsCreateCalendarRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedule/v1/absence-calendars`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: absenceCalendarsCreateCalendarRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/schedule/v1/absence-calendars',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(absenceCalendarsCreateCalendarRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Absence Calendars
         * @param {string} [employeeId] Employee ID
         * @param {string} [type] Absence Type ID
         * @param {Array<number>} [yearIn] Year calendar
         * @param {number} [limit] Limit results
         * @param {number} [page] Request a specific page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (employeeId?: string, type?: string, yearIn?: Array<number>, limit?: number, page?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedule/v1/absence-calendars`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (employeeId !== undefined) {
                localVarQueryParameter['employeeId'] = employeeId;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (yearIn) {
                localVarQueryParameter['year[in]'] = yearIn.join(COLLECTION_FORMATS.csv);
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/schedule/v1/absence-calendars',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Absence Calendar
         * @param {string} id Calendar ID
         * @param {AbsenceCalendarsUpdateByIdRequest} [absenceCalendarsUpdateByIdRequest] Absence Calendar object that needs to be updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateById: async (id: string, absenceCalendarsUpdateByIdRequest?: AbsenceCalendarsUpdateByIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateById', 'id', id)
            const localVarPath = `/schedule/v1/absence-calendars/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: absenceCalendarsUpdateByIdRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/schedule/v1/absence-calendars/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(absenceCalendarsUpdateByIdRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AbsenceCalendarsApi - functional programming interface
 * @export
 */
export const AbsenceCalendarsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AbsenceCalendarsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Absence Calendar
         * @param {AbsenceCalendarsApiCreateCalendarRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCalendar(requestParameters: AbsenceCalendarsApiCreateCalendarRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceCalendarsCreateCalendarResponse>> {
            const absenceCalendarsCreateCalendarRequest: AbsenceCalendarsCreateCalendarRequest = {
                employeeId: requestParameters.employeeId,
                absenceTypeId: requestParameters.absenceTypeId,
                year: requestParameters.year,
                daysOff: requestParameters.daysOff
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCalendar(absenceCalendarsCreateCalendarRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List Absence Calendars
         * @param {AbsenceCalendarsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: AbsenceCalendarsApiListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceCalendarsListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.employeeId, requestParameters.type, requestParameters.yearIn, requestParameters.limit, requestParameters.page, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update Absence Calendar
         * @param {AbsenceCalendarsApiUpdateByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateById(requestParameters: AbsenceCalendarsApiUpdateByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceCalendarsUpdateByIdResponse>> {
            const absenceCalendarsUpdateByIdRequest: AbsenceCalendarsUpdateByIdRequest = {
                daysOff: requestParameters.daysOff
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateById(requestParameters.id, absenceCalendarsUpdateByIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AbsenceCalendarsApi - factory interface
 * @export
 */
export const AbsenceCalendarsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AbsenceCalendarsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Absence Calendar
         * @param {AbsenceCalendarsApiCreateCalendarRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCalendar(requestParameters: AbsenceCalendarsApiCreateCalendarRequest, options?: AxiosRequestConfig): AxiosPromise<AbsenceCalendarsCreateCalendarResponse> {
            return localVarFp.createCalendar(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Absence Calendars
         * @param {AbsenceCalendarsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: AbsenceCalendarsApiListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<AbsenceCalendarsListResponse> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Absence Calendar
         * @param {AbsenceCalendarsApiUpdateByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateById(requestParameters: AbsenceCalendarsApiUpdateByIdRequest, options?: AxiosRequestConfig): AxiosPromise<AbsenceCalendarsUpdateByIdResponse> {
            return localVarFp.updateById(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createCalendar operation in AbsenceCalendarsApi.
 * @export
 * @interface AbsenceCalendarsApiCreateCalendarRequest
 */
export type AbsenceCalendarsApiCreateCalendarRequest = {
    
} & AbsenceCalendarsCreateCalendarRequest

/**
 * Request parameters for list operation in AbsenceCalendarsApi.
 * @export
 * @interface AbsenceCalendarsApiListRequest
 */
export type AbsenceCalendarsApiListRequest = {
    
    /**
    * Employee ID
    * @type {string}
    * @memberof AbsenceCalendarsApiList
    */
    readonly employeeId?: string
    
    /**
    * Absence Type ID
    * @type {string}
    * @memberof AbsenceCalendarsApiList
    */
    readonly type?: string
    
    /**
    * Year calendar
    * @type {Array<number>}
    * @memberof AbsenceCalendarsApiList
    */
    readonly yearIn?: Array<number>
    
    /**
    * Limit results
    * @type {number}
    * @memberof AbsenceCalendarsApiList
    */
    readonly limit?: number
    
    /**
    * Request a specific page
    * @type {number}
    * @memberof AbsenceCalendarsApiList
    */
    readonly page?: number
    
}

/**
 * Request parameters for updateById operation in AbsenceCalendarsApi.
 * @export
 * @interface AbsenceCalendarsApiUpdateByIdRequest
 */
export type AbsenceCalendarsApiUpdateByIdRequest = {
    
    /**
    * Calendar ID
    * @type {string}
    * @memberof AbsenceCalendarsApiUpdateById
    */
    readonly id: string
    
} & AbsenceCalendarsUpdateByIdRequest

/**
 * AbsenceCalendarsApiGenerated - object-oriented interface
 * @export
 * @class AbsenceCalendarsApiGenerated
 * @extends {BaseAPI}
 */
export class AbsenceCalendarsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Create Absence Calendar
     * @param {AbsenceCalendarsApiCreateCalendarRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceCalendarsApiGenerated
     */
    public createCalendar(requestParameters: AbsenceCalendarsApiCreateCalendarRequest, options?: AxiosRequestConfig) {
        return AbsenceCalendarsApiFp(this.configuration).createCalendar(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Absence Calendars
     * @param {AbsenceCalendarsApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceCalendarsApiGenerated
     */
    public list(requestParameters: AbsenceCalendarsApiListRequest = {}, options?: AxiosRequestConfig) {
        return AbsenceCalendarsApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Absence Calendar
     * @param {AbsenceCalendarsApiUpdateByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceCalendarsApiGenerated
     */
    public updateById(requestParameters: AbsenceCalendarsApiUpdateByIdRequest, options?: AxiosRequestConfig) {
        return AbsenceCalendarsApiFp(this.configuration).updateById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
