/* tslint:disable */
/* eslint-disable */
/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CheckTypesListTypesResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CheckTypesApi - axios parameter creator
 * @export
 */
export const CheckTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Check Types
         * @param {number} [limit] Limit results
         * @param {number} [page] Request a specific page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTypes: async (limit?: number, page?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedule/v1/check-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/schedule/v1/check-types',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CheckTypesApi - functional programming interface
 * @export
 */
export const CheckTypesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CheckTypesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Check Types
         * @param {CheckTypesApiListTypesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTypes(requestParameters: CheckTypesApiListTypesRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckTypesListTypesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTypes(requestParameters.limit, requestParameters.page, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CheckTypesApi - factory interface
 * @export
 */
export const CheckTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CheckTypesApiFp(configuration)
    return {
        /**
         * 
         * @summary List Check Types
         * @param {CheckTypesApiListTypesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTypes(requestParameters: CheckTypesApiListTypesRequest = {}, options?: AxiosRequestConfig): AxiosPromise<CheckTypesListTypesResponse> {
            return localVarFp.listTypes(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listTypes operation in CheckTypesApi.
 * @export
 * @interface CheckTypesApiListTypesRequest
 */
export type CheckTypesApiListTypesRequest = {
    
    /**
    * Limit results
    * @type {number}
    * @memberof CheckTypesApiListTypes
    */
    readonly limit?: number
    
    /**
    * Request a specific page
    * @type {number}
    * @memberof CheckTypesApiListTypes
    */
    readonly page?: number
    
}

/**
 * CheckTypesApiGenerated - object-oriented interface
 * @export
 * @class CheckTypesApiGenerated
 * @extends {BaseAPI}
 */
export class CheckTypesApiGenerated extends BaseAPI {
    /**
     * 
     * @summary List Check Types
     * @param {CheckTypesApiListTypesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CheckTypesApiGenerated
     */
    public listTypes(requestParameters: CheckTypesApiListTypesRequest = {}, options?: AxiosRequestConfig) {
        return CheckTypesApiFp(this.configuration).listTypes(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
