/* tslint:disable */
/* eslint-disable */
/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { EmployeeDepartmentAssignationsAssignDepartmentToEmployeeRequest } from '../models';
// @ts-ignore
import { EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponse } from '../models';
// @ts-ignore
import { EmployeeDepartmentAssignationsListResponse } from '../models';
// @ts-ignore
import { EmployeeDepartmentAssignationsUnassignRequest } from '../models';
// @ts-ignore
import { EmployeeDepartmentAssignationsUnassignResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeeDepartmentAssignationsApi - axios parameter creator
 * @export
 */
export const EmployeeDepartmentAssignationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Assign an employee to a department
         * @param {EmployeeDepartmentAssignationsAssignDepartmentToEmployeeRequest} employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest Employee object needs to be assigned to Department object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignDepartmentToEmployee: async (employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest: EmployeeDepartmentAssignationsAssignDepartmentToEmployeeRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest' is not null or undefined
            assertParamExists('assignDepartmentToEmployee', 'employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest', employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest)
            const localVarPath = `/core/v3/employee-department-assignations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/core/v3/employee-department-assignations',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List employee department assignation
         * @param {string} [employeeId] Find Assignation by employeeId
         * @param {string} [departmentId] Find Assignation by departmentId
         * @param {number} [limit] Limit assignations
         * @param {number} [page] Request a specific page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (employeeId?: string, departmentId?: string, limit?: number, page?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/core/v3/employee-department-assignations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (employeeId !== undefined) {
                localVarQueryParameter['employeeId'] = employeeId;
            }

            if (departmentId !== undefined) {
                localVarQueryParameter['departmentId'] = departmentId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/core/v3/employee-department-assignations',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unassign employee from department
         * @param {EmployeeDepartmentAssignationsUnassignRequest} employeeDepartmentAssignationsUnassignRequest Employee object needs to be unassigned to Department object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassign: async (employeeDepartmentAssignationsUnassignRequest: EmployeeDepartmentAssignationsUnassignRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeDepartmentAssignationsUnassignRequest' is not null or undefined
            assertParamExists('unassign', 'employeeDepartmentAssignationsUnassignRequest', employeeDepartmentAssignationsUnassignRequest)
            const localVarPath = `/core/v3/employee-department-assignations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeeDepartmentAssignationsUnassignRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/core/v3/employee-department-assignations',
                httpMethod: 'DELETE'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeeDepartmentAssignationsUnassignRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeDepartmentAssignationsApi - functional programming interface
 * @export
 */
export const EmployeeDepartmentAssignationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeDepartmentAssignationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Assign an employee to a department
         * @param {EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignDepartmentToEmployee(requestParameters: EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponse>> {
            const employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest: EmployeeDepartmentAssignationsAssignDepartmentToEmployeeRequest = {
                employeeId: requestParameters.employeeId,
                departmentId: requestParameters.departmentId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignDepartmentToEmployee(employeeDepartmentAssignationsAssignDepartmentToEmployeeRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List employee department assignation
         * @param {EmployeeDepartmentAssignationsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: EmployeeDepartmentAssignationsApiListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeDepartmentAssignationsListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.employeeId, requestParameters.departmentId, requestParameters.limit, requestParameters.page, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Unassign employee from department
         * @param {EmployeeDepartmentAssignationsApiUnassignRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unassign(requestParameters: EmployeeDepartmentAssignationsApiUnassignRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeDepartmentAssignationsUnassignResponse>> {
            const employeeDepartmentAssignationsUnassignRequest: EmployeeDepartmentAssignationsUnassignRequest = {
                employeeId: requestParameters.employeeId,
                departmentId: requestParameters.departmentId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.unassign(employeeDepartmentAssignationsUnassignRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeeDepartmentAssignationsApi - factory interface
 * @export
 */
export const EmployeeDepartmentAssignationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeDepartmentAssignationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Assign an employee to a department
         * @param {EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignDepartmentToEmployee(requestParameters: EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest, options?: AxiosRequestConfig): AxiosPromise<EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponse> {
            return localVarFp.assignDepartmentToEmployee(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List employee department assignation
         * @param {EmployeeDepartmentAssignationsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: EmployeeDepartmentAssignationsApiListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<EmployeeDepartmentAssignationsListResponse> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unassign employee from department
         * @param {EmployeeDepartmentAssignationsApiUnassignRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassign(requestParameters: EmployeeDepartmentAssignationsApiUnassignRequest, options?: AxiosRequestConfig): AxiosPromise<EmployeeDepartmentAssignationsUnassignResponse> {
            return localVarFp.unassign(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for assignDepartmentToEmployee operation in EmployeeDepartmentAssignationsApi.
 * @export
 * @interface EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest
 */
export type EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest = {
    
} & EmployeeDepartmentAssignationsAssignDepartmentToEmployeeRequest

/**
 * Request parameters for list operation in EmployeeDepartmentAssignationsApi.
 * @export
 * @interface EmployeeDepartmentAssignationsApiListRequest
 */
export type EmployeeDepartmentAssignationsApiListRequest = {
    
    /**
    * Find Assignation by employeeId
    * @type {string}
    * @memberof EmployeeDepartmentAssignationsApiList
    */
    readonly employeeId?: string
    
    /**
    * Find Assignation by departmentId
    * @type {string}
    * @memberof EmployeeDepartmentAssignationsApiList
    */
    readonly departmentId?: string
    
    /**
    * Limit assignations
    * @type {number}
    * @memberof EmployeeDepartmentAssignationsApiList
    */
    readonly limit?: number
    
    /**
    * Request a specific page
    * @type {number}
    * @memberof EmployeeDepartmentAssignationsApiList
    */
    readonly page?: number
    
}

/**
 * Request parameters for unassign operation in EmployeeDepartmentAssignationsApi.
 * @export
 * @interface EmployeeDepartmentAssignationsApiUnassignRequest
 */
export type EmployeeDepartmentAssignationsApiUnassignRequest = {
    
} & EmployeeDepartmentAssignationsUnassignRequest

/**
 * EmployeeDepartmentAssignationsApiGenerated - object-oriented interface
 * @export
 * @class EmployeeDepartmentAssignationsApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeeDepartmentAssignationsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Assign an employee to a department
     * @param {EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeDepartmentAssignationsApiGenerated
     */
    public assignDepartmentToEmployee(requestParameters: EmployeeDepartmentAssignationsApiAssignDepartmentToEmployeeRequest, options?: AxiosRequestConfig) {
        return EmployeeDepartmentAssignationsApiFp(this.configuration).assignDepartmentToEmployee(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List employee department assignation
     * @param {EmployeeDepartmentAssignationsApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeDepartmentAssignationsApiGenerated
     */
    public list(requestParameters: EmployeeDepartmentAssignationsApiListRequest = {}, options?: AxiosRequestConfig) {
        return EmployeeDepartmentAssignationsApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unassign employee from department
     * @param {EmployeeDepartmentAssignationsApiUnassignRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeDepartmentAssignationsApiGenerated
     */
    public unassign(requestParameters: EmployeeDepartmentAssignationsApiUnassignRequest, options?: AxiosRequestConfig) {
        return EmployeeDepartmentAssignationsApiFp(this.configuration).unassign(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
