/* tslint:disable */
/* eslint-disable */
/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { VacationDayOffListResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * VacationDayOffApi - axios parameter creator
 * @export
 */
export const VacationDayOffApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List Vacation Day Off
         * @param {Array<string>} [employeeIds] The id of the employees
         * @param {string | Date} [from] First day of search period
         * @param {string | Date} [to] Last day of search period
         * @param {number} [page] Request a specific page
         * @param {number} [limit] Limit vacation requests
         * @param {string} [orderBy] field1 asc, field2 desc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (employeeIds?: Array<string>, from?: string | Date, to?: string | Date, page?: number, limit?: number, orderBy?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedule/v1/vacation-day-off`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (employeeIds) {
                localVarQueryParameter['employeeIds'] = employeeIds.join(COLLECTION_FORMATS.csv);
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString().substr(0,10) :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString().substr(0,10) :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/schedule/v1/vacation-day-off',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VacationDayOffApi - functional programming interface
 * @export
 */
export const VacationDayOffApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VacationDayOffApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List Vacation Day Off
         * @param {VacationDayOffApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: VacationDayOffApiListRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VacationDayOffListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.employeeIds, requestParameters.from, requestParameters.to, requestParameters.page, requestParameters.limit, requestParameters.orderBy, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * VacationDayOffApi - factory interface
 * @export
 */
export const VacationDayOffApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VacationDayOffApiFp(configuration)
    return {
        /**
         * 
         * @summary List Vacation Day Off
         * @param {VacationDayOffApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: VacationDayOffApiListRequest, options?: AxiosRequestConfig): AxiosPromise<VacationDayOffListResponse> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for list operation in VacationDayOffApi.
 * @export
 * @interface VacationDayOffApiListRequest
 */
export type VacationDayOffApiListRequest = {
    
    /**
    * The id of the employees
    * @type {Array<string>}
    * @memberof VacationDayOffApiList
    */
    readonly employeeIds?: Array<string>
    
    /**
    * First day of search period
    * @type {string | Date}
    * @memberof VacationDayOffApiList
    */
    readonly from?: string | Date
    
    /**
    * Last day of search period
    * @type {string | Date}
    * @memberof VacationDayOffApiList
    */
    readonly to?: string | Date
    
    /**
    * Request a specific page
    * @type {number}
    * @memberof VacationDayOffApiList
    */
    readonly page?: number
    
    /**
    * Limit vacation requests
    * @type {number}
    * @memberof VacationDayOffApiList
    */
    readonly limit?: number
    
    /**
    * field1 asc, field2 desc
    * @type {string}
    * @memberof VacationDayOffApiList
    */
    readonly orderBy?: string
    
}

/**
 * VacationDayOffApiGenerated - object-oriented interface
 * @export
 * @class VacationDayOffApiGenerated
 * @extends {BaseAPI}
 */
export class VacationDayOffApiGenerated extends BaseAPI {
    /**
     * 
     * @summary List Vacation Day Off
     * @param {VacationDayOffApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VacationDayOffApiGenerated
     */
    public list(requestParameters: VacationDayOffApiListRequest, options?: AxiosRequestConfig) {
        return VacationDayOffApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
