/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceDayOffRequestsCreateDayOffRequestRequestDaysOffInner } from './absence-day-off-requests-create-day-off-request-request-days-off-inner';

/**
 * 
 * @export
 * @interface AbsenceDayOffRequestsCreateDayOffRequestRequest
 */
export interface AbsenceDayOffRequestsCreateDayOffRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestRequest
     */
    'employeeId': string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestRequest
     */
    'absenceTypeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestRequest
     */
    'type': AbsenceDayOffRequestsCreateDayOffRequestRequestTypeEnum;
    /**
     * 
     * @type {Array<AbsenceDayOffRequestsCreateDayOffRequestRequestDaysOffInner>}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestRequest
     */
    'daysOff': Array<AbsenceDayOffRequestsCreateDayOffRequestRequestDaysOffInner>;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestRequest
     */
    'comment'?: string;
}

type AbsenceDayOffRequestsCreateDayOffRequestRequestTypeEnum = 'create' | 'delete'


