/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendar } from './absence-day-off-requests-create-day-off-request-response-data-absence-calendar';
import { AbsenceDayOffRequestsCreateDayOffRequestResponseDataDaysOffInner } from './absence-day-off-requests-create-day-off-request-response-data-days-off-inner';
import { AbsenceDayOffRequestsCreateDayOffRequestResponseDataEmployee } from './absence-day-off-requests-create-day-off-request-response-data-employee';

/**
 * 
 * @export
 * @interface AbsenceDayOffRequestsCreateDayOffRequestResponseData
 */
export interface AbsenceDayOffRequestsCreateDayOffRequestResponseData {
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendar}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'absenceCalendar'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendar;
    /**
     * 
     * @type {AbsenceDayOffRequestsCreateDayOffRequestResponseDataEmployee}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'employee'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataEmployee;
    /**
     * 
     * @type {Array<AbsenceDayOffRequestsCreateDayOffRequestResponseDataDaysOffInner>}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'daysOff'?: Array<AbsenceDayOffRequestsCreateDayOffRequestResponseDataDaysOffInner>;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'status'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'type'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'resolutionComment'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'resolvedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseData
     */
    'deletedAt'?: string;
}

type AbsenceDayOffRequestsCreateDayOffRequestResponseDataStatusEnum = 'accepted' | 'rejected' | 'pending'
type AbsenceDayOffRequestsCreateDayOffRequestResponseDataTypeEnum = 'create' | 'delete'


