/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeCompany } from './absence-day-off-requests-create-day-off-request-response-data-absence-calendar-absence-type-company';

/**
 * 
 * @export
 * @interface AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
 */
export interface AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType {
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'needsValidation'?: boolean;
    /**
     * 
     * @type {AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeCompany}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'company'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeCompany;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'deletedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'type'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType
     */
    'pickMode'?: AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypePickModeEnum;
}

type AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeTypeEnum = 'normal' | 'private'
type AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypePickModeEnum = 'by_days' | 'by_time_range'


