/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceDayOffRequestsCreateDayOffRequestResponseData } from './absence-day-off-requests-create-day-off-request-response-data';
import { AbsenceDayOffRequestsCreateDayOffRequestResponseMeta } from './absence-day-off-requests-create-day-off-request-response-meta';

/**
 * 
 * @export
 * @interface AbsenceDayOffRequestsCreateDayOffRequestResponse
 */
export interface AbsenceDayOffRequestsCreateDayOffRequestResponse {
    /**
     * 
     * @type {AbsenceDayOffRequestsCreateDayOffRequestResponseData}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponse
     */
    'data'?: AbsenceDayOffRequestsCreateDayOffRequestResponseData;
    /**
     * 
     * @type {AbsenceDayOffRequestsCreateDayOffRequestResponseMeta}
     * @memberof AbsenceDayOffRequestsCreateDayOffRequestResponse
     */
    'meta'?: AbsenceDayOffRequestsCreateDayOffRequestResponseMeta;
}

