/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceDayOffRequestsDeleteRequestByIdResponseMeta } from './absence-day-off-requests-delete-request-by-id-response-meta';

/**
 * 
 * @export
 * @interface AbsenceDayOffRequestsDeleteRequestByIdResponse
 */
export interface AbsenceDayOffRequestsDeleteRequestByIdResponse {
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayOffRequestsDeleteRequestByIdResponse
     */
    'data'?: string;
    /**
     * 
     * @type {AbsenceDayOffRequestsDeleteRequestByIdResponseMeta}
     * @memberof AbsenceDayOffRequestsDeleteRequestByIdResponse
     */
    'meta'?: AbsenceDayOffRequestsDeleteRequestByIdResponseMeta;
}

