/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
 */
export interface AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany {
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
     */
    'notificationEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsListResponseDataInnerAbsenceTypeCompany
     */
    'updatedAt'?: string;
}

