/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceCalendarsListResponseDataInnerDaysOffInner } from './absence-calendars-list-response-data-inner-days-off-inner';
import { AbsenceCalendarsUpdateByIdResponseDataAbsenceType } from './absence-calendars-update-by-id-response-data-absence-type';
import { AbsenceCalendarsUpdateByIdResponseDataEmployee } from './absence-calendars-update-by-id-response-data-employee';

/**
 * 
 * @export
 * @interface AbsenceCalendarsUpdateByIdResponseData
 */
export interface AbsenceCalendarsUpdateByIdResponseData {
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {AbsenceCalendarsUpdateByIdResponseDataEmployee}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'employee'?: AbsenceCalendarsUpdateByIdResponseDataEmployee;
    /**
     * 
     * @type {Array<AbsenceCalendarsListResponseDataInnerDaysOffInner>}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'daysOff'?: Array<AbsenceCalendarsListResponseDataInnerDaysOffInner>;
    /**
     * 
     * @type {number}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'maxDaysOff'?: number;
    /**
     * 
     * @type {number}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'year'?: number;
    /**
     * 
     * @type {AbsenceCalendarsUpdateByIdResponseDataAbsenceType}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'absenceType'?: AbsenceCalendarsUpdateByIdResponseDataAbsenceType;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsUpdateByIdResponseData
     */
    'deletedAt'?: string | null;
}

