/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceCalendarsCreateCalendarResponseDataAbsenceTypeCompany } from './absence-calendars-create-calendar-response-data-absence-type-company';

/**
 * 
 * @export
 * @interface AbsenceCalendarsCreateCalendarResponseDataAbsenceType
 */
export interface AbsenceCalendarsCreateCalendarResponseDataAbsenceType {
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'needsValidation'?: boolean;
    /**
     * 
     * @type {AbsenceCalendarsCreateCalendarResponseDataAbsenceTypeCompany}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'company'?: AbsenceCalendarsCreateCalendarResponseDataAbsenceTypeCompany;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'deletedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'type'?: AbsenceCalendarsCreateCalendarResponseDataAbsenceTypeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AbsenceCalendarsCreateCalendarResponseDataAbsenceType
     */
    'pickMode'?: AbsenceCalendarsCreateCalendarResponseDataAbsenceTypePickModeEnum;
}

type AbsenceCalendarsCreateCalendarResponseDataAbsenceTypeTypeEnum = 'normal' | 'private'
type AbsenceCalendarsCreateCalendarResponseDataAbsenceTypePickModeEnum = 'by_days' | 'by_time_range'


