/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceDayOffRequestsAcceptRequestResponseData } from './absence-day-off-requests-accept-request-response-data';
import { AbsenceDayOffRequestsAcceptRequestResponseMeta } from './absence-day-off-requests-accept-request-response-meta';

/**
 * 
 * @export
 * @interface AbsenceDayOffRequestsAcceptRequestResponse
 */
export interface AbsenceDayOffRequestsAcceptRequestResponse {
    /**
     * 
     * @type {AbsenceDayOffRequestsAcceptRequestResponseData}
     * @memberof AbsenceDayOffRequestsAcceptRequestResponse
     */
    'data'?: AbsenceDayOffRequestsAcceptRequestResponseData;
    /**
     * 
     * @type {AbsenceDayOffRequestsAcceptRequestResponseMeta}
     * @memberof AbsenceDayOffRequestsAcceptRequestResponse
     */
    'meta'?: AbsenceDayOffRequestsAcceptRequestResponseMeta;
}

