/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AgreementsListResponseDataInner
 */
export interface AgreementsListResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'color'?: string;
    /**
     * 
     * @type {number}
     * @memberof AgreementsListResponseDataInner
     */
    'annualHours'?: number;
    /**
     * 
     * @type {number}
     * @memberof AgreementsListResponseDataInner
     */
    'additionalHoursPercent'?: number;
    /**
     * 
     * @type {number}
     * @memberof AgreementsListResponseDataInner
     */
    'totalAdditionalHours'?: number;
    /**
     * 
     * @type {number}
     * @memberof AgreementsListResponseDataInner
     */
    'maxDaysToWork'?: number;
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgreementsListResponseDataInner
     */
    'updatedAt'?: string;
}

