/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AgreementsCreateNewAgreementRequest
 */
export interface AgreementsCreateNewAgreementRequest {
    /**
     * Agreement name
     * @type {string}
     * @memberof AgreementsCreateNewAgreementRequest
     */
    'name': string;
    /**
     * Agreement code
     * @type {string}
     * @memberof AgreementsCreateNewAgreementRequest
     */
    'code': string;
    /**
     * Color of agreement
     * @type {string}
     * @memberof AgreementsCreateNewAgreementRequest
     */
    'color': string;
    /**
     * Annual hours
     * @type {number}
     * @memberof AgreementsCreateNewAgreementRequest
     */
    'annualHours': number;
}

