/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContractsGetByEmployeeIdResponseDataInner } from './contracts-get-by-employee-id-response-data-inner';
import { ContractsGetByEmployeeIdResponseMeta } from './contracts-get-by-employee-id-response-meta';

/**
 * 
 * @export
 * @interface ContractsGetByEmployeeIdResponse
 */
export interface ContractsGetByEmployeeIdResponse {
    /**
     * 
     * @type {Array<ContractsGetByEmployeeIdResponseDataInner>}
     * @memberof ContractsGetByEmployeeIdResponse
     */
    'data'?: Array<ContractsGetByEmployeeIdResponseDataInner>;
    /**
     * 
     * @type {ContractsGetByEmployeeIdResponseMeta}
     * @memberof ContractsGetByEmployeeIdResponse
     */
    'meta'?: ContractsGetByEmployeeIdResponseMeta;
}

