/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType
 */
export interface ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType {
    /**
     * 
     * @type {string}
     * @memberof ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType
     */
    'editable'?: boolean;
}

