/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContractsGetCurrentContractByEmployeeIdResponseData } from './contracts-get-current-contract-by-employee-id-response-data';
import { ContractsGetCurrentContractByEmployeeIdResponseMeta } from './contracts-get-current-contract-by-employee-id-response-meta';

/**
 * 
 * @export
 * @interface ContractsGetCurrentContractByEmployeeIdResponse
 */
export interface ContractsGetCurrentContractByEmployeeIdResponse {
    /**
     * 
     * @type {ContractsGetCurrentContractByEmployeeIdResponseData}
     * @memberof ContractsGetCurrentContractByEmployeeIdResponse
     */
    'data'?: ContractsGetCurrentContractByEmployeeIdResponseData;
    /**
     * 
     * @type {ContractsGetCurrentContractByEmployeeIdResponseMeta}
     * @memberof ContractsGetCurrentContractByEmployeeIdResponse
     */
    'meta'?: ContractsGetCurrentContractByEmployeeIdResponseMeta;
}

