/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomersUpdateCustomerResponseData } from './customers-update-customer-response-data';
import { CustomersUpdateCustomerResponseMeta } from './customers-update-customer-response-meta';

/**
 * 
 * @export
 * @interface CustomersUpdateCustomerResponse
 */
export interface CustomersUpdateCustomerResponse {
    /**
     * 
     * @type {CustomersUpdateCustomerResponseData}
     * @memberof CustomersUpdateCustomerResponse
     */
    'data'?: CustomersUpdateCustomerResponseData;
    /**
     * 
     * @type {CustomersUpdateCustomerResponseMeta}
     * @memberof CustomersUpdateCustomerResponse
     */
    'meta'?: CustomersUpdateCustomerResponseMeta;
}

