/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomFieldsUpdateFieldByIdRequest
 */
export interface CustomFieldsUpdateFieldByIdRequest {
    /**
     * The name of the custom field
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdRequest
     */
    'slug'?: string;
}

