/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomFieldsDeleteFieldResponseMeta } from './custom-fields-delete-field-response-meta';

/**
 * 
 * @export
 * @interface CustomFieldsDeleteFieldResponse
 */
export interface CustomFieldsDeleteFieldResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsDeleteFieldResponse
     */
    'data'?: string;
    /**
     * 
     * @type {CustomFieldsDeleteFieldResponseMeta}
     * @memberof CustomFieldsDeleteFieldResponse
     */
    'meta'?: CustomFieldsDeleteFieldResponseMeta;
}

