/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomFieldsUpdateFieldByIdResponseData
 */
export interface CustomFieldsUpdateFieldByIdResponseData {
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'type'?: CustomFieldsUpdateFieldByIdResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFieldsUpdateFieldByIdResponseData
     */
    'updatedAt'?: string;
}

type CustomFieldsUpdateFieldByIdResponseDataTypeEnum = 'text'


