/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentsListDirectoriesResponseDataInner } from './documents-list-directories-response-data-inner';
import { DocumentsListDirectoriesResponseMeta } from './documents-list-directories-response-meta';

/**
 * 
 * @export
 * @interface DocumentsListDirectoriesResponse
 */
export interface DocumentsListDirectoriesResponse {
    /**
     * 
     * @type {Array<DocumentsListDirectoriesResponseDataInner>}
     * @memberof DocumentsListDirectoriesResponse
     */
    'data'?: Array<DocumentsListDirectoriesResponseDataInner>;
    /**
     * 
     * @type {DocumentsListDirectoriesResponseMeta}
     * @memberof DocumentsListDirectoriesResponse
     */
    'meta'?: DocumentsListDirectoriesResponseMeta;
}

