/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeScheduleTemplatesListTemplatesResponseDataInner } from './employee-schedule-templates-list-templates-response-data-inner';
import { EmployeeScheduleTemplatesListTemplatesResponseMeta } from './employee-schedule-templates-list-templates-response-meta';

/**
 * 
 * @export
 * @interface EmployeeScheduleTemplatesListTemplatesResponse
 */
export interface EmployeeScheduleTemplatesListTemplatesResponse {
    /**
     * 
     * @type {Array<EmployeeScheduleTemplatesListTemplatesResponseDataInner>}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponse
     */
    'data'?: Array<EmployeeScheduleTemplatesListTemplatesResponseDataInner>;
    /**
     * 
     * @type {EmployeeScheduleTemplatesListTemplatesResponseMeta}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponse
     */
    'meta'?: EmployeeScheduleTemplatesListTemplatesResponseMeta;
}

