/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeAssignationsRolesAssignRoleResponseMeta } from './employee-assignations-roles-assign-role-response-meta';

/**
 * 
 * @export
 * @interface EmployeeAssignationsRolesAssignRoleResponse
 */
export interface EmployeeAssignationsRolesAssignRoleResponse {
    /**
     * 
     * @type {string}
     * @memberof EmployeeAssignationsRolesAssignRoleResponse
     */
    'data'?: string;
    /**
     * 
     * @type {EmployeeAssignationsRolesAssignRoleResponseMeta}
     * @memberof EmployeeAssignationsRolesAssignRoleResponse
     */
    'meta'?: EmployeeAssignationsRolesAssignRoleResponseMeta;
}

