/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeManagersAssignResponseDataEmployee } from './employee-managers-assign-response-data-employee';
import { EmployeeManagersAssignResponseDataManager } from './employee-managers-assign-response-data-manager';

/**
 * 
 * @export
 * @interface EmployeeManagersAssignResponseData
 */
export interface EmployeeManagersAssignResponseData {
    /**
     * 
     * @type {string}
     * @memberof EmployeeManagersAssignResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {EmployeeManagersAssignResponseDataManager}
     * @memberof EmployeeManagersAssignResponseData
     */
    'manager'?: EmployeeManagersAssignResponseDataManager;
    /**
     * 
     * @type {EmployeeManagersAssignResponseDataEmployee}
     * @memberof EmployeeManagersAssignResponseData
     */
    'employee'?: EmployeeManagersAssignResponseDataEmployee;
    /**
     * 
     * @type {string}
     * @memberof EmployeeManagersAssignResponseData
     */
    'permission'?: EmployeeManagersAssignResponseDataPermissionEnum;
    /**
     * 
     * @type {number}
     * @memberof EmployeeManagersAssignResponseData
     */
    'order'?: EmployeeManagersAssignResponseDataOrderEnum;
    /**
     * 
     * @type {string}
     * @memberof EmployeeManagersAssignResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeManagersAssignResponseData
     */
    'updatedAt'?: string;
}

type EmployeeManagersAssignResponseDataPermissionEnum = 'check' | 'vacation'
type EmployeeManagersAssignResponseDataOrderEnum = 0 | 1


