/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeDepartmentAssignationsUnassignRequest
 */
export interface EmployeeDepartmentAssignationsUnassignRequest {
    /**
     * The identifier of the employee
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsUnassignRequest
     */
    'employeeId': string;
    /**
     * The identifier of the department
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsUnassignRequest
     */
    'departmentId': string;
}

