/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest
 */
export interface EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest {
    /**
     * Employee UUID
     * @type {string}
     * @memberof EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest
     */
    'employeeId': string;
    /**
     * Schedule template UUID
     * @type {string}
     * @memberof EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest
     */
    'scheduleTemplateId': string;
    /**
     * Start date
     * @type {string}
     * @memberof EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest
     */
    'startDate': string;
    /**
     * End date
     * @type {string}
     * @memberof EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest
     */
    'endDate'?: string;
}

