/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeAgreementsAssignEmployeeRequest
 */
export interface EmployeeAgreementsAssignEmployeeRequest {
    /**
     * Agreement UUID
     * @type {string}
     * @memberof EmployeeAgreementsAssignEmployeeRequest
     */
    'agreementId': string;
    /**
     * Employee UUID
     * @type {string}
     * @memberof EmployeeAgreementsAssignEmployeeRequest
     */
    'employeeId': string;
    /**
     * Start date
     * @type {string}
     * @memberof EmployeeAgreementsAssignEmployeeRequest
     */
    'startDate': string;
}

