/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseDataEmployee } from './employee-department-assignations-assign-department-to-employee-response-data-employee';
import { RolesGetAllResponseDataInner } from './roles-get-all-response-data-inner';

/**
 * 
 * @export
 * @interface EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData
 */
export interface EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData {
    /**
     * 
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseDataEmployee}
     * @memberof EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData
     */
    'employee'?: EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseDataEmployee;
    /**
     * 
     * @type {RolesGetAllResponseDataInner}
     * @memberof EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData
     */
    'department'?: RolesGetAllResponseDataInner;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsAssignDepartmentToEmployeeResponseData
     */
    'updatedAt'?: string;
}

