/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner } from './employee-schedule-templates-list-templates-response-data-inner20240101-inner';

/**
 * 
 * @export
 * @interface EmployeeScheduleTemplatesListTemplatesResponseDataInner
 */
export interface EmployeeScheduleTemplatesListTemplatesResponseDataInner {
    /**
     * 
     * @type {Array<EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner>}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner
     */
    '2024-01-01'?: Array<EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner>;
}

