/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeOfficeAssignationsListAssignationsResponseDataInner } from './employee-office-assignations-list-assignations-response-data-inner';
import { EmployeeOfficeAssignationsListAssignationsResponseMeta } from './employee-office-assignations-list-assignations-response-meta';

/**
 * 
 * @export
 * @interface EmployeeOfficeAssignationsListAssignationsResponse
 */
export interface EmployeeOfficeAssignationsListAssignationsResponse {
    /**
     * 
     * @type {Array<EmployeeOfficeAssignationsListAssignationsResponseDataInner>}
     * @memberof EmployeeOfficeAssignationsListAssignationsResponse
     */
    'data'?: Array<EmployeeOfficeAssignationsListAssignationsResponseDataInner>;
    /**
     * 
     * @type {EmployeeOfficeAssignationsListAssignationsResponseMeta}
     * @memberof EmployeeOfficeAssignationsListAssignationsResponse
     */
    'meta'?: EmployeeOfficeAssignationsListAssignationsResponseMeta;
}

