/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData } from './employee-office-assignations-assign-employee-to-office-response-data';
import { EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseMeta } from './employee-office-assignations-assign-employee-to-office-response-meta';

/**
 * 
 * @export
 * @interface EmployeeOfficeAssignationsAssignEmployeeToOfficeResponse
 */
export interface EmployeeOfficeAssignationsAssignEmployeeToOfficeResponse {
    /**
     * 
     * @type {EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData}
     * @memberof EmployeeOfficeAssignationsAssignEmployeeToOfficeResponse
     */
    'data'?: EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData;
    /**
     * 
     * @type {EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseMeta}
     * @memberof EmployeeOfficeAssignationsAssignEmployeeToOfficeResponse
     */
    'meta'?: EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseMeta;
}

