/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeDepartmentAssignationsListResponseDataInnerEmployee } from './employee-department-assignations-list-response-data-inner-employee';
import { RolesGetAllResponseDataInner } from './roles-get-all-response-data-inner';

/**
 * 
 * @export
 * @interface EmployeeDepartmentAssignationsListResponseDataInner
 */
export interface EmployeeDepartmentAssignationsListResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsListResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {EmployeeDepartmentAssignationsListResponseDataInnerEmployee}
     * @memberof EmployeeDepartmentAssignationsListResponseDataInner
     */
    'employee'?: EmployeeDepartmentAssignationsListResponseDataInnerEmployee;
    /**
     * 
     * @type {RolesGetAllResponseDataInner}
     * @memberof EmployeeDepartmentAssignationsListResponseDataInner
     */
    'department'?: RolesGetAllResponseDataInner;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsListResponseDataInner
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDepartmentAssignationsListResponseDataInner
     */
    'updatedAt'?: string;
}

