/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101InnerWeekdaysRanges } from './employee-schedule-templates-list-templates-response-data-inner20240101-inner-weekdays-ranges';

/**
 * 
 * @export
 * @interface EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
 */
export interface EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner {
    /**
     * 
     * @type {string}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'mondayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'tuesdayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'wednesdayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'thursdayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'fridayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'saturdayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'sundayMinutes'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'currentDayMinutes'?: number;
    /**
     * 
     * @type {EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101InnerWeekdaysRanges}
     * @memberof EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101Inner
     */
    'weekdaysRanges'?: EmployeeScheduleTemplatesListTemplatesResponseDataInner20240101InnerWeekdaysRanges;
}

