/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeesCreateNewEmployeeResponseData } from './employees-create-new-employee-response-data';
import { EmployeesCreateNewEmployeeResponseMeta } from './employees-create-new-employee-response-meta';

/**
 * 
 * @export
 * @interface EmployeesCreateNewEmployeeResponse
 */
export interface EmployeesCreateNewEmployeeResponse {
    /**
     * 
     * @type {EmployeesCreateNewEmployeeResponseData}
     * @memberof EmployeesCreateNewEmployeeResponse
     */
    'data'?: EmployeesCreateNewEmployeeResponseData;
    /**
     * 
     * @type {EmployeesCreateNewEmployeeResponseMeta}
     * @memberof EmployeesCreateNewEmployeeResponse
     */
    'meta'?: EmployeesCreateNewEmployeeResponseMeta;
}

