/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeOfficeAssignationsUnassignEmployeeResponseMeta } from './employee-office-assignations-unassign-employee-response-meta';

/**
 * 
 * @export
 * @interface EmployeeOfficeAssignationsUnassignEmployeeResponse
 */
export interface EmployeeOfficeAssignationsUnassignEmployeeResponse {
    /**
     * 
     * @type {string}
     * @memberof EmployeeOfficeAssignationsUnassignEmployeeResponse
     */
    'data'?: string;
    /**
     * 
     * @type {EmployeeOfficeAssignationsUnassignEmployeeResponseMeta}
     * @memberof EmployeeOfficeAssignationsUnassignEmployeeResponse
     */
    'meta'?: EmployeeOfficeAssignationsUnassignEmployeeResponseMeta;
}

