/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HolidayCalendarsCreateNewCalendarRequestDaysOffInner } from './holiday-calendars-create-new-calendar-request-days-off-inner';

/**
 * 
 * @export
 * @interface HolidayCalendarsCreateNewCalendarRequest
 */
export interface HolidayCalendarsCreateNewCalendarRequest {
    /**
     * The name of the holidays
     * @type {string}
     * @memberof HolidayCalendarsCreateNewCalendarRequest
     */
    'name': string;
    /**
     * 
     * @type {Array<HolidayCalendarsCreateNewCalendarRequestDaysOffInner>}
     * @memberof HolidayCalendarsCreateNewCalendarRequest
     */
    'daysOff': Array<HolidayCalendarsCreateNewCalendarRequestDaysOffInner>;
}

