/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface HolidayCalendarsUpdateByIdResponseDataDayOffInner
 */
export interface HolidayCalendarsUpdateByIdResponseDataDayOffInner {
    /**
     * 
     * @type {string}
     * @memberof HolidayCalendarsUpdateByIdResponseDataDayOffInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof HolidayCalendarsUpdateByIdResponseDataDayOffInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof HolidayCalendarsUpdateByIdResponseDataDayOffInner
     */
    'date'?: string;
}

