/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HolidayCalendarsUpdateByIdResponseData } from './holiday-calendars-update-by-id-response-data';
import { HolidayCalendarsUpdateByIdResponseMeta } from './holiday-calendars-update-by-id-response-meta';

/**
 * 
 * @export
 * @interface HolidayCalendarsUpdateByIdResponse
 */
export interface HolidayCalendarsUpdateByIdResponse {
    /**
     * 
     * @type {HolidayCalendarsUpdateByIdResponseData}
     * @memberof HolidayCalendarsUpdateByIdResponse
     */
    'data'?: HolidayCalendarsUpdateByIdResponseData;
    /**
     * 
     * @type {HolidayCalendarsUpdateByIdResponseMeta}
     * @memberof HolidayCalendarsUpdateByIdResponse
     */
    'meta'?: HolidayCalendarsUpdateByIdResponseMeta;
}

