/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HolidayCalendarsGetByIdResponseDataDayOffInner } from './holiday-calendars-get-by-id-response-data-day-off-inner';

/**
 * 
 * @export
 * @interface HolidayCalendarsGetByIdResponseData
 */
export interface HolidayCalendarsGetByIdResponseData {
    /**
     * 
     * @type {string}
     * @memberof HolidayCalendarsGetByIdResponseData
     */
    'id'?: string;
    /**
     * The name of the holidays
     * @type {string}
     * @memberof HolidayCalendarsGetByIdResponseData
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof HolidayCalendarsGetByIdResponseData
     */
    'companyId'?: string;
    /**
     * 
     * @type {Array<HolidayCalendarsGetByIdResponseDataDayOffInner>}
     * @memberof HolidayCalendarsGetByIdResponseData
     */
    'dayOff'?: Array<HolidayCalendarsGetByIdResponseDataDayOffInner>;
    /**
     * 
     * @type {string}
     * @memberof HolidayCalendarsGetByIdResponseData
     */
    'typeId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof HolidayCalendarsGetByIdResponseData
     */
    'default'?: boolean;
}

