/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HolidaysUnassignHolidayCalendarToEmployeeResponseMeta } from './holidays-unassign-holiday-calendar-to-employee-response-meta';

/**
 * 
 * @export
 * @interface HolidaysUnassignHolidayCalendarToEmployeeResponse
 */
export interface HolidaysUnassignHolidayCalendarToEmployeeResponse {
    /**
     * 
     * @type {string}
     * @memberof HolidaysUnassignHolidayCalendarToEmployeeResponse
     */
    'data'?: string;
    /**
     * 
     * @type {HolidaysUnassignHolidayCalendarToEmployeeResponseMeta}
     * @memberof HolidaysUnassignHolidayCalendarToEmployeeResponse
     */
    'meta'?: HolidaysUnassignHolidayCalendarToEmployeeResponseMeta;
}

