/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OfficesGetAllResponseDataInnerCoordinates } from './offices-get-all-response-data-inner-coordinates';

/**
 * 
 * @export
 * @interface OfficesGetAllResponseDataInner
 */
export interface OfficesGetAllResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof OfficesGetAllResponseDataInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficesGetAllResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficesGetAllResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OfficesGetAllResponseDataInner
     */
    'address'?: string;
    /**
     * 
     * @type {OfficesGetAllResponseDataInnerCoordinates}
     * @memberof OfficesGetAllResponseDataInner
     */
    'coordinates'?: OfficesGetAllResponseDataInnerCoordinates;
    /**
     * 
     * @type {number}
     * @memberof OfficesGetAllResponseDataInner
     */
    'radio'?: number;
}

