/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
 */
export interface ProjectsUpdateProjectByIdResponseDataParentProjectCustomer {
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'customerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdResponseDataParentProjectCustomer
     */
    'deletedAt'?: string;
}

