/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsUpdateProjectByIdRequest
 */
export interface ProjectsUpdateProjectByIdRequest {
    /**
     * The description of the project
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'description'?: string;
    /**
     * The name of the project
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'name': string;
    /**
     * The id of the parent project
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'parentProjectId'?: string;
    /**
     * The id of the customer
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'customerId'?: string;
    /**
     * The price of the project
     * @type {number}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'price'?: number;
    /**
     * The start date of the project
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'startDate'?: string;
    /**
     * The end date of the project
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'endDate'?: string;
    /**
     * The id of the employee manager
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'managerId'?: string;
    /**
     * The status of the project
     * @type {string}
     * @memberof ProjectsUpdateProjectByIdRequest
     */
    'status'?: ProjectsUpdateProjectByIdRequestStatusEnum;
}

type ProjectsUpdateProjectByIdRequestStatusEnum = 'active' | 'inactive' | 'paused'


