/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsListResponseDataInnerCustomer } from './projects-list-response-data-inner-customer';
import { ProjectsListResponseDataInnerManager } from './projects-list-response-data-inner-manager';
import { ProjectsListResponseDataInnerParentProject } from './projects-list-response-data-inner-parent-project';

/**
 * 
 * @export
 * @interface ProjectsListResponseDataInner
 */
export interface ProjectsListResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof ProjectsListResponseDataInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsListResponseDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsListResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {ProjectsListResponseDataInnerParentProject}
     * @memberof ProjectsListResponseDataInner
     */
    'parentProject'?: ProjectsListResponseDataInnerParentProject | null;
    /**
     * 
     * @type {ProjectsListResponseDataInnerCustomer}
     * @memberof ProjectsListResponseDataInner
     */
    'customer'?: ProjectsListResponseDataInnerCustomer;
    /**
     * 
     * @type {number}
     * @memberof ProjectsListResponseDataInner
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectsListResponseDataInner
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsListResponseDataInner
     */
    'endDate'?: string;
    /**
     * 
     * @type {ProjectsListResponseDataInnerManager}
     * @memberof ProjectsListResponseDataInner
     */
    'manager'?: ProjectsListResponseDataInnerManager;
    /**
     * 
     * @type {string}
     * @memberof ProjectsListResponseDataInner
     */
    'status'?: ProjectsListResponseDataInnerStatusEnum;
}

type ProjectsListResponseDataInnerStatusEnum = 'active' | 'inactive' | 'paused'


