/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecruitmentGetCandidateByIdResponseData } from './recruitment-get-candidate-by-id-response-data';
import { RecruitmentGetCandidateByIdResponseMeta } from './recruitment-get-candidate-by-id-response-meta';

/**
 * 
 * @export
 * @interface RecruitmentGetCandidateByIdResponse
 */
export interface RecruitmentGetCandidateByIdResponse {
    /**
     * 
     * @type {RecruitmentGetCandidateByIdResponseData}
     * @memberof RecruitmentGetCandidateByIdResponse
     */
    'data'?: RecruitmentGetCandidateByIdResponseData;
    /**
     * 
     * @type {RecruitmentGetCandidateByIdResponseMeta}
     * @memberof RecruitmentGetCandidateByIdResponse
     */
    'meta'?: RecruitmentGetCandidateByIdResponseMeta;
}

