/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecruitmentUpdateCandidateResponseDataVacancyCategory } from './recruitment-update-candidate-response-data-vacancy-category';
import { RecruitmentUpdateCandidateResponseDataVacancyLocationVacancy } from './recruitment-update-candidate-response-data-vacancy-location-vacancy';
import { RecruitmentUpdateCandidateResponseDataVacancyScheduleType } from './recruitment-update-candidate-response-data-vacancy-schedule-type';

/**
 * 
 * @export
 * @interface RecruitmentUpdateCandidateResponseDataVacancy
 */
export interface RecruitmentUpdateCandidateResponseDataVacancy {
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'department'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'contactType'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'experience'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'createdById'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'status'?: RecruitmentUpdateCandidateResponseDataVacancyStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'openedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'public'?: boolean;
    /**
     * 
     * @type {RecruitmentUpdateCandidateResponseDataVacancyLocationVacancy}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'locationVacancy'?: RecruitmentUpdateCandidateResponseDataVacancyLocationVacancy;
    /**
     * 
     * @type {RecruitmentUpdateCandidateResponseDataVacancyScheduleType}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'scheduleType'?: RecruitmentUpdateCandidateResponseDataVacancyScheduleType;
    /**
     * 
     * @type {RecruitmentUpdateCandidateResponseDataVacancyCategory}
     * @memberof RecruitmentUpdateCandidateResponseDataVacancy
     */
    'category'?: RecruitmentUpdateCandidateResponseDataVacancyCategory;
}

type RecruitmentUpdateCandidateResponseDataVacancyStatusEnum = 'open' | 'closed' | 'draft'


