/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RecruitmentCreateCandidateRequest
 */
export interface RecruitmentCreateCandidateRequest {
    /**
     * The first name of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'firstName': string;
    /**
     * The last name of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'email': string;
    /**
     * The phone number of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'phone': string;
    /**
     * The LinkedIn URL of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'linkedinURL'?: string;
    /**
     * The desired salary of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'desiredSalary'?: string;
    /**
     * The start work date of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'startWorkDate'?: string;
    /**
     * The web of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'web'?: string;
    /**
     * The location of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'location'?: string;
    /**
     * The identifier of the vacancy where the candidate will be added
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'vacancyId': string;
    /**
     * The identifier of the status of the candidate
     * @type {string}
     * @memberof RecruitmentCreateCandidateRequest
     */
    'statusId'?: string;
}

