/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecruitmentUploadCandidateDocumentResponseMeta } from './recruitment-upload-candidate-document-response-meta';

/**
 * 
 * @export
 * @interface RecruitmentUploadCandidateDocumentResponse
 */
export interface RecruitmentUploadCandidateDocumentResponse {
    /**
     * 
     * @type {string}
     * @memberof RecruitmentUploadCandidateDocumentResponse
     */
    'data'?: string;
    /**
     * 
     * @type {RecruitmentUploadCandidateDocumentResponseMeta}
     * @memberof RecruitmentUploadCandidateDocumentResponse
     */
    'meta'?: RecruitmentUploadCandidateDocumentResponseMeta;
}

