/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RecruitmentCreateCandidateResponseDataStatus
 */
export interface RecruitmentCreateCandidateResponseDataStatus {
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'companyId'?: string;
    /**
     * 
     * @type {number}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'order'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecruitmentCreateCandidateResponseDataStatus
     */
    'vacancyId'?: string;
}

