/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SecurityGetTokenInfoResponseData } from './security-get-token-info-response-data';
import { SecurityGetTokenInfoResponseMeta } from './security-get-token-info-response-meta';

/**
 * 
 * @export
 * @interface SecurityGetTokenInfoResponse
 */
export interface SecurityGetTokenInfoResponse {
    /**
     * 
     * @type {SecurityGetTokenInfoResponseData}
     * @memberof SecurityGetTokenInfoResponse
     */
    'data'?: SecurityGetTokenInfoResponseData;
    /**
     * 
     * @type {SecurityGetTokenInfoResponseMeta}
     * @memberof SecurityGetTokenInfoResponse
     */
    'meta'?: SecurityGetTokenInfoResponseMeta;
}

