/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StatisticsListWorkedHoursByEmployeeResponseDataInner } from './statistics-list-worked-hours-by-employee-response-data-inner';
import { StatisticsListWorkedHoursByEmployeeResponseMeta } from './statistics-list-worked-hours-by-employee-response-meta';

/**
 * 
 * @export
 * @interface StatisticsListWorkedHoursByEmployeeResponse
 */
export interface StatisticsListWorkedHoursByEmployeeResponse {
    /**
     * 
     * @type {Array<StatisticsListWorkedHoursByEmployeeResponseDataInner>}
     * @memberof StatisticsListWorkedHoursByEmployeeResponse
     */
    'data'?: Array<StatisticsListWorkedHoursByEmployeeResponseDataInner>;
    /**
     * 
     * @type {StatisticsListWorkedHoursByEmployeeResponseMeta}
     * @memberof StatisticsListWorkedHoursByEmployeeResponse
     */
    'meta'?: StatisticsListWorkedHoursByEmployeeResponseMeta;
}

