/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TimeEntriesStopTimeEntryOutResponseData } from './time-entries-stop-time-entry-out-response-data';
import { TimeEntriesStopTimeEntryOutResponseMeta } from './time-entries-stop-time-entry-out-response-meta';

/**
 * 
 * @export
 * @interface TimeEntriesStopTimeEntryOutResponse
 */
export interface TimeEntriesStopTimeEntryOutResponse {
    /**
     * 
     * @type {TimeEntriesStopTimeEntryOutResponseData}
     * @memberof TimeEntriesStopTimeEntryOutResponse
     */
    'data'?: TimeEntriesStopTimeEntryOutResponseData;
    /**
     * 
     * @type {TimeEntriesStopTimeEntryOutResponseMeta}
     * @memberof TimeEntriesStopTimeEntryOutResponse
     */
    'meta'?: TimeEntriesStopTimeEntryOutResponseMeta;
}

