/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkEntriesStartNewEntryRequestWorkEntryInCoordinates } from './work-entries-start-new-entry-request-work-entry-in-coordinates';

/**
 * 
 * @export
 * @interface TimeEntriesStartEntryRequest
 */
export interface TimeEntriesStartEntryRequest {
    /**
     * 
     * @type {string}
     * @memberof TimeEntriesStartEntryRequest
     */
    'employeeId': string;
    /**
     * 
     * @type {string}
     * @memberof TimeEntriesStartEntryRequest
     */
    'projectId'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeEntriesStartEntryRequest
     */
    'tagIds'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TimeEntriesStartEntryRequest
     */
    'comment'?: string;
    /**
     * 
     * @type {WorkEntriesStartNewEntryRequestWorkEntryInCoordinates}
     * @memberof TimeEntriesStartEntryRequest
     */
    'coordinates'?: WorkEntriesStartNewEntryRequestWorkEntryInCoordinates;
}

