/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CoreV3EmployeeCustomFieldsInner } from './core-v3-employee-custom-fields-inner';
import { VacationCalendarsListCalendarsResponseDataInnerEmployeeCompany } from './vacation-calendars-list-calendars-response-data-inner-employee-company';

/**
 * 
 * @export
 * @interface VacationCalendarsListCalendarsResponseDataInnerEmployee
 */
export interface VacationCalendarsListCalendarsResponseDataInnerEmployee {
    /**
     * The description of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'workStatus'?: VacationCalendarsListCalendarsResponseDataInnerEmployeeWorkStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'imageProfileURL'?: string;
    /**
     * 
     * @type {number}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'code'?: number;
    /**
     * 
     * @type {number}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'pin'?: number;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'phone'?: string;
    /**
     * 
     * @type {VacationCalendarsListCalendarsResponseDataInnerEmployeeCompany}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'company'?: VacationCalendarsListCalendarsResponseDataInnerEmployeeCompany;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'gender'?: VacationCalendarsListCalendarsResponseDataInnerEmployeeGenderEnum;
    /**
     * The identifier of your internal employee contract
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'contractId'?: string;
    /**
     * The National Identity Document of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'nid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'identityNumberType'?: VacationCalendarsListCalendarsResponseDataInnerEmployeeIdentityNumberTypeEnum;
    /**
     * The Social Security Number of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'ssn'?: string;
    /**
     * The Price per hour of the employee
     * @type {number}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'pricePerHour'?: number;
    /**
     * The Account Number of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'accountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {Array<CoreV3EmployeeCustomFieldsInner>}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'customFields'?: Array<CoreV3EmployeeCustomFieldsInner>;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'status'?: VacationCalendarsListCalendarsResponseDataInnerEmployeeStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'children'?: number;
    /**
     * 
     * @type {number}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'disability'?: number;
    /**
     * The Address of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'address'?: string;
    /**
     * The postal code of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'postalCode'?: string;
    /**
     * The city of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'city'?: string;
    /**
     * The province of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'province'?: string;
    /**
     * The country of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'country'?: string;
    /**
     * The nationality of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'nationality'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'personalMail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'maritalStatus'?: string;
    /**
     * The emergency phone of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'emergencyPhone'?: string;
    /**
     * The salary range of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'salaryRange'?: string;
    /**
     * The study level of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'studyLevel'?: string;
    /**
     * The professional category code of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'professionalCategoryCode'?: string;
    /**
     * The professional category description of the employee
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'professionalCategoryDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationCalendarsListCalendarsResponseDataInnerEmployee
     */
    'bic'?: string;
}

type VacationCalendarsListCalendarsResponseDataInnerEmployeeWorkStatusEnum = 'online' | 'offline' | 'paused' | 'remote'
type VacationCalendarsListCalendarsResponseDataInnerEmployeeGenderEnum = 'female' | 'male' | 'no_response'
type VacationCalendarsListCalendarsResponseDataInnerEmployeeIdentityNumberTypeEnum = 'dni' | 'nie' | 'rut' | 'other'
type VacationCalendarsListCalendarsResponseDataInnerEmployeeStatusEnum = 'active' | 'inactive'


