/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VacationCalendarsListCalendarsResponseDataInnerDaysOffInner } from './vacation-calendars-list-calendars-response-data-inner-days-off-inner';
import { VacationDayOffRequestsListResponseDataInnerVacationCalendarEmployee } from './vacation-day-off-requests-list-response-data-inner-vacation-calendar-employee';
import { VacationDayOffRequestsListResponseDataInnerVacationCalendarVacationConfiguration } from './vacation-day-off-requests-list-response-data-inner-vacation-calendar-vacation-configuration';

/**
 * 
 * @export
 * @interface VacationDayOffRequestsListResponseDataInnerVacationCalendar
 */
export interface VacationDayOffRequestsListResponseDataInnerVacationCalendar {
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'id'?: string;
    /**
     * 
     * @type {VacationDayOffRequestsListResponseDataInnerVacationCalendarEmployee}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'employee'?: VacationDayOffRequestsListResponseDataInnerVacationCalendarEmployee;
    /**
     * 
     * @type {Array<VacationCalendarsListCalendarsResponseDataInnerDaysOffInner>}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'daysOff'?: Array<VacationCalendarsListCalendarsResponseDataInnerDaysOffInner>;
    /**
     * 
     * @type {number}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'maxDaysOff'?: number;
    /**
     * 
     * @type {number}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'year'?: number;
    /**
     * 
     * @type {VacationDayOffRequestsListResponseDataInnerVacationCalendarVacationConfiguration}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'vacationConfiguration'?: VacationDayOffRequestsListResponseDataInnerVacationCalendarVacationConfiguration;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsListResponseDataInnerVacationCalendar
     */
    'deletedAt'?: string;
}

