/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VacationDayOffRequestsListResponseDataInner } from './vacation-day-off-requests-list-response-data-inner';
import { VacationDayOffRequestsListResponseMeta } from './vacation-day-off-requests-list-response-meta';

/**
 * 
 * @export
 * @interface VacationDayOffRequestsListResponse
 */
export interface VacationDayOffRequestsListResponse {
    /**
     * 
     * @type {Array<VacationDayOffRequestsListResponseDataInner>}
     * @memberof VacationDayOffRequestsListResponse
     */
    'data'?: Array<VacationDayOffRequestsListResponseDataInner>;
    /**
     * 
     * @type {VacationDayOffRequestsListResponseMeta}
     * @memberof VacationDayOffRequestsListResponse
     */
    'meta'?: VacationDayOffRequestsListResponseMeta;
}

