/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VacationCalendarsListCalendarsResponseDataInnerDaysOffInner } from './vacation-calendars-list-calendars-response-data-inner-days-off-inner';
import { VacationDayOffRequestsAcceptRequestResponseDataEmployee } from './vacation-day-off-requests-accept-request-response-data-employee';
import { VacationDayOffRequestsAcceptRequestResponseDataVacationCalendar } from './vacation-day-off-requests-accept-request-response-data-vacation-calendar';

/**
 * 
 * @export
 * @interface VacationDayOffRequestsAcceptRequestResponseData
 */
export interface VacationDayOffRequestsAcceptRequestResponseData {
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {VacationDayOffRequestsAcceptRequestResponseDataVacationCalendar}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'vacationCalendar'?: VacationDayOffRequestsAcceptRequestResponseDataVacationCalendar;
    /**
     * 
     * @type {VacationDayOffRequestsAcceptRequestResponseDataEmployee}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'employee'?: VacationDayOffRequestsAcceptRequestResponseDataEmployee;
    /**
     * 
     * @type {Array<VacationCalendarsListCalendarsResponseDataInnerDaysOffInner>}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'daysOff'?: Array<VacationCalendarsListCalendarsResponseDataInnerDaysOffInner>;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'status'?: VacationDayOffRequestsAcceptRequestResponseDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'type'?: VacationDayOffRequestsAcceptRequestResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'resolutionComment'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'resolvedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VacationDayOffRequestsAcceptRequestResponseData
     */
    'deletedAt'?: string;
}

type VacationDayOffRequestsAcceptRequestResponseDataStatusEnum = 'accepted' | 'rejected' | 'pending'
type VacationDayOffRequestsAcceptRequestResponseDataTypeEnum = 'create' | 'delete'


