/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VacationDayOffRequestsCreateRequestResponseData } from './vacation-day-off-requests-create-request-response-data';
import { VacationDayOffRequestsCreateRequestResponseMeta } from './vacation-day-off-requests-create-request-response-meta';

/**
 * 
 * @export
 * @interface VacationDayOffRequestsCreateRequestResponse
 */
export interface VacationDayOffRequestsCreateRequestResponse {
    /**
     * 
     * @type {VacationDayOffRequestsCreateRequestResponseData}
     * @memberof VacationDayOffRequestsCreateRequestResponse
     */
    'data'?: VacationDayOffRequestsCreateRequestResponseData;
    /**
     * 
     * @type {VacationDayOffRequestsCreateRequestResponseMeta}
     * @memberof VacationDayOffRequestsCreateRequestResponse
     */
    'meta'?: VacationDayOffRequestsCreateRequestResponseMeta;
}

