/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VacationConfigurationsListConfigurationsResponseMeta
 */
export interface VacationConfigurationsListConfigurationsResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof VacationConfigurationsListConfigurationsResponseMeta
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof VacationConfigurationsListConfigurationsResponseMeta
     */
    'lastPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof VacationConfigurationsListConfigurationsResponseMeta
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof VacationConfigurationsListConfigurationsResponseMeta
     */
    'perPage'?: number;
}

