/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkEntriesCreateNewEntryResponseData } from './work-entries-create-new-entry-response-data';
import { WorkEntriesCreateNewEntryResponseMeta } from './work-entries-create-new-entry-response-meta';

/**
 * 
 * @export
 * @interface WorkEntriesCreateNewEntryResponse
 */
export interface WorkEntriesCreateNewEntryResponse {
    /**
     * 
     * @type {WorkEntriesCreateNewEntryResponseData}
     * @memberof WorkEntriesCreateNewEntryResponse
     */
    'data'?: WorkEntriesCreateNewEntryResponseData;
    /**
     * 
     * @type {WorkEntriesCreateNewEntryResponseMeta}
     * @memberof WorkEntriesCreateNewEntryResponse
     */
    'meta'?: WorkEntriesCreateNewEntryResponseMeta;
}

