/*
Sesame Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 3.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkEntriesEndLastEntryResponseDataEmployee } from './work-entries-end-last-entry-response-data-employee';
import { WorkEntriesEndLastEntryResponseDataWorkEntryIn } from './work-entries-end-last-entry-response-data-work-entry-in';
import { WorkEntriesEndLastEntryResponseDataWorkEntryOut } from './work-entries-end-last-entry-response-data-work-entry-out';

/**
 * 
 * @export
 * @interface WorkEntriesEndLastEntryResponseData
 */
export interface WorkEntriesEndLastEntryResponseData {
    /**
     * 
     * @type {string}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'workCheckTypeId'?: string;
    /**
     * 
     * @type {WorkEntriesEndLastEntryResponseDataEmployee}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'employee'?: WorkEntriesEndLastEntryResponseDataEmployee;
    /**
     * 
     * @type {string}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'workEntryType'?: string;
    /**
     * 
     * @type {WorkEntriesEndLastEntryResponseDataWorkEntryIn}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'workEntryIn'?: WorkEntriesEndLastEntryResponseDataWorkEntryIn;
    /**
     * 
     * @type {WorkEntriesEndLastEntryResponseDataWorkEntryOut}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'workEntryOut'?: WorkEntriesEndLastEntryResponseDataWorkEntryOut;
    /**
     * 
     * @type {number}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'workedSeconds'?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkEntriesEndLastEntryResponseData
     */
    'deletedAt'?: string;
}

